name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Assuming you have a requirements.txt file

    - name: Run Python script with API keys
      env:
        GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        HF_API_KEY: ${{ secrets.HF_API_KEY }}
        LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
      run: |
        python app.py
